name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  auto-assign:
    uses: ./.github/workflows/auto-assign.yml
  auto-approve:
    needs: auto-assign
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js from `.node-version`
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'

      - uses: hmarr/auto-approve-action@v3
