name: Increment Major Version

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Permission gradlew
        run: chmod +x gradlew

      - name: Bump Major Version
        run: ./gradlew bumpMajorVersion

      - name: Get Version
        run: |
          echo "::set-output name=VERSION_CODE::$(./gradlew -q printVersionCode)"
          echo "::set-output name=VERSION_NAME::$(./gradlew -q printVersionName)"
        id: version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-app-major-version-${{ steps.version.outputs.VERSION_NAME }}-${{ steps.version.outputs.VERSION_CODE }}
          base: release
          title: "chore: 🤖 versionName: ${{ steps.version.outputs.VERSION_NAME }} / versionCode: ${{ steps.version.outputs.VERSION_CODE }}"
          commit-message: "chore: 🤖 versionName: `${{ steps.version.outputs.VERSION_NAME }}` / versionCode: `${{ steps.version.outputs.VERSION_CODE }}`"
